version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-8080}:${FRONTEND_PORT:-8080}"
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT:-8080}
      - BACKEND_PORT=${BACKEND_PORT:-3000}
      - NODE_ENV=${NODE_ENV:-production}
      - MODE=${MODE:-dev}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-3000}:${BACKEND_PORT:-3000}"
    environment:
      - BACKEND_PORT=${BACKEND_PORT:-3000}
      - FRONTEND_PORT=${FRONTEND_PORT:-8080} 
      - NODE_ENV=${NODE_ENV:-production}
      - MODE=${MODE:-dev}
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
