let itemsData = [
  {
    id: 0,
    name: "Квартира в центре города",
    description: "Просторная квартира с новым ремонтом.",
    location: "Москва",
    type: ItemTypes.REAL_ESTATE,
    propertyType: "Квартира",
    area: 60,
    rooms: 2,
    price: 8000000,
  },
  {
    id: 1,
    name: "Новый автомобиль",
    description: "Продается новый автомобиль, пробег 0.",
    location: "Санкт-Петербург",
    type: ItemTypes.AUTO,
    brand: "Toyota",
    model: "Camry",
    year: 2022,
    mileage: 0,
    price: 2500000,
  },
  {
    id: 2,
    name: "Услуги репетитора",
    description: "Опытный репетитор по математике и физике.",
    location: "Казань",
    type: ItemTypes.SERVICES,
    serviceType: "Репетиторство",
    experience: 5,
    cost: 1500,
  },
  {
    id: 3,
    name: "Просторный дом",
    description: "Дом с участком 10 соток.",
    location: "Екатеринбург",
    type: ItemTypes.REAL_ESTATE,
    propertyType: "Дом",
    area: 150,
    rooms: 5,
    price: 15000000,
  },
  {
    id: 4,
    name: "Скутер",
    description: "Скутер в отличном состоянии.",
    location: "Москва",
    type: ItemTypes.AUTO,
    brand: "Honda",
    model: "Dio",
    year: 2020,
    mileage: 5000,
    price: 70000,
  },
  {
    id: 5,
    name: "Услуги фотографа",
    description: "Профессиональная фотосессия.",
    location: "Нижний Новгород",
    type: ItemTypes.SERVICES,
    serviceType: "Фотография",
    experience: 3,
    cost: 5000,
  },
  {
    id: 6,
    name: "Услуги фотографа",
    description: "Профессиональная фотосессия.",
    location: "Нижний Новгород",
    type: ItemTypes.SERVICES,
    serviceType: "Фотография",
    experience: 3,
    cost: 5000,
  },
];
